//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        public int id_caracteristica { get; set; }
        public string caracteristica1 { get; set; }
        public Nullable<int> id_tipo { get; set; }
    }
}
