//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enlace_Hijo_Detalle
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_enlace_hijo { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> visitas { get; set; }
        public string nombre_contacto { get; set; }
        public string email_contacto { get; set; }
        public string usuarioWhatsapp { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
    }
}
