//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enlace
    {
        public int id_enlace { get; set; }
        public string web { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
    }
}
