//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enlace_Hijo_Validate
    {
        public int id { get; set; }
        public Nullable<int> id_enlace { get; set; }
        public Nullable<long> id_property { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> catched_date { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
    }
}
