//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ScrappingEntities : DbContext
    {
        public ScrappingEntities()
            : base("name=ScrappingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enlace> Enlace { get; set; }
        public virtual DbSet<Caracteristica_Tipo> Caracteristica_Tipo { get; set; }
        public virtual DbSet<Enlace_Hijo_Validate> Enlace_Hijo_Validate { get; set; }
        public virtual DbSet<Enlace_Hijo_Caracteristica> Enlace_Hijo_Caracteristica { get; set; }
        public virtual DbSet<Caracteristica> Caracteristica { get; set; }
        public virtual DbSet<Enlace_Hijo_Detalle> Enlace_Hijo_Detalle { get; set; }
        public virtual DbSet<Enlace_Hijo> Enlace_Hijo { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_ENLACE_HIJO_VALIDATE(Nullable<int> id_enlace)
        {
            var id_enlaceParameter = id_enlace.HasValue ?
                new ObjectParameter("id_enlace", id_enlace) :
                new ObjectParameter("id_enlace", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ENLACE_HIJO_VALIDATE", id_enlaceParameter);
        }
    }
}
